services:
  - type: web
    name: bamspam
    runtime: python
    plan: free
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
